// Quiz questions and choices

let quizQuestions = [
    {
        question: "A DOUBLE CHECK BACKFLOW PREVENTION ASSEMBLY TEST AND MAINTENANCE REPORT SHALL INCLUDE ALL OF THE FOLLOWING INFORMATION EXCEPT THE:",
        choices: ["ADDRESS OF THE INSTALLATION", "SERIAL NUMBER OF THE ASSEMBLY", "TEST RESULTS OF CHECK VALVE NUMBER ONE (1)", "TEST RESULTS OF CHECK VALVE NUMBER TWO (2)", "DIFFERENTIAL PRESSURE RELIEF VALVE DISCHARGE READING"],
        correctAnswer: 4,
    },
    {
        question: "THE BY-PASS LINE OF AN APPROVED BACKFLOW PREVENTION ASSEMBLY MUST CONTAIN AN APPROVED ASSEMBLY OF EQUAL:",
        choices: ["CORROSION RESISTANCE", "CFLOW CAPACITY", "PROTECTION", "SIZE", "TEMPERATURE RATING"],
        correctAnswer: 2,
    },
    {
        question: "AN ATMOSPHERIC TYPE VACUUM BREAKER SHALL NOT BE SUBJECTED TO WATER PRESSURE FOR PERIODS THAN ______ HOURS.",
        choices: ["SIX (6)", "EIGHT (8)", "TWELVE (12)", "TWENTY-FOUR (24)", "NONE OF THE ABOVE"],
        correctAnswer: 2,
    },
    {
        question: "S IT IS POSSIBLE FOR A PERFECT VACUUM AT SEA LEVEL TO RAISE WATER IN A PIPE APPROXIMATELY _________  FEET.",
        choices: ["TWENTY-FIVE (25)", "THIRTY (30)", "THIRTY-TWO (32)", "THIRTY-FOUR (34)", "THIRTY-SIX (36)"],
        correctAnswer: 3,
    },
    {
        question: "WHAT IS THE MOST DESIRABLE PLACE TO INSTALL A BACKFLOW PREVENTION DEVICE AND/OR ASSEMBLY?",
        choices: ["IN A REINFORCED CONCRETE PIT", "IN AN ACCESSIBLE LOCATION ABOVE GROUND", "UNDERGROUND, WITH A MINIMUM OF TWELVE (12) INCHES OF COVER", "AT OR ABOVE CEILING HEIGHT, TO PROTECT IT FROM VANDALISM", "BEHIND THE BOILER OR EQUIPMENT SERVED, SO IT CAN BE WORKED ON WHEN THE EQUIPMENT IS REMOVED"],
        correctAnswer: 1,
    },
    {
      question: "WHICH OF THE FOLLOWING CONDITIONS COULD RESULT IN WATER CONTAMINATION THROUGH A CROSS-CONNECTION?",
      choices: ["A VACUUM CREATED BY THE IMPROPER USE OF WATER HAMMER ARRESTERS", "THE USE OF SELF CLOSING LAVATORY FAUCETS", "TURNING OFF SERVICE TO A MULTI-STORY BUILDING AND ALLOWING THE WATER SUPPLY TO DRAIN", "A VACUUM CREATED BY THE USE OF QUICK CLOSING VALVES ON THE LOWER FLOORS OF A BUILDING EXCEEDING TEN (10) FLOORS IN HEIGHT", "THE INSTALLATION OF WATER CONSERVING FIXTURES, INTO A BUILDING DESIGNED PRIOR TO THEIR REQUIRED US"],
      correctAnswer: 2,
  },
  {
    question: "WHAT IS ANOTHER TERM THAT DESCRIBES WATER QUALITY AS A HEALTH HAZARD RESULTING FROM BACKFLOW?",
    choices: ["ISOLATION", "CONTAMINATION", "CROSS-CONNECTION", "POLLUTION", "CONTAINED"],
    correctAnswer: 1,
},
{
  question: "THE VENTURI EFFECT STATES THAT WHEN THE WATER VELOCITY WITHIN THE PIPE INCREASES, THE PRESSURE:",
  choices: ["WILL INCREASE PROPORTIONATELY", "WILL REMAIN CONSTANT", "COMPRESSES EXCESS VOLUMES OF WATER", "DECREASES", "CREATES BACKPRESSURE"],
  correctAnswer: 3,
},
{
  question: "THE DEGREE OF HAZARD IS:",
  choices: ["THE ACCEPTABLE TEMPERATURE RANGE OF A NON-POTABLE WATER SOURCE", "THE ANGLE OF THE BACKFLOW PREVENTER", "BASED UPON THE QUALITY OF A NON POTABLE WATER SOURCE", "DISTANCE BETWEEN THE CROSS-CONNECTION AND THE BACKFLOW PREVENTER", "THE ENGINEER’S SPECIFIED ELEVATION OF NON-POTABLE PIPING"],
  correctAnswer: 2,
},
{
  question: "BACKFLOW MAY BE DESCRIBED AS EITHER:",
  choices: ["BACKPRESSURE OR BACKSIPHONAGE", "CONTAMINATION OR POLLUTION", "CONTAINMENT AND ISOLATION", "DIRECT AND/OR INDIRECT", "HIGH TEMPERATURE OR LOW TEMPERATURE"],
  correctAnswer: 0,
},
{
  question: "THE FEDERAL LAW PLACING RESPONSIBILITY FOR THE PROTECTION OF THE PUBLIC WATER SUPPLY ON THE PURVEYOR OF WATER IS THE:",
  choices: ["ENVIRONMENTAL PROTECTION AGENCY’S PRIMARY DRINKING WATER REGULATIONS", "OCCUPATIONAL SAFETY AND HEALTH ADMINISTRATION REGULATIONS", "SAFE DRINKING WATER ACT", "FOOD AND DRUG ADMINISTRATION’S UNIFORM PLUMBING CODE", "CLEAN WATER ACT"],
  correctAnswer: 2,
},
{
  question: "HOW MANY INCHES MUST A PRESSURE TYPE VACUUM BREAKER ASSEMBLY BE INSTALLED ABOVE ALL DOWNSTREAM PIPING?",
  choices: ["SIX (6)", "TWELVE (12)", "EIGHTEEN (18)", "TWENTY-FOUR (24)", "ONE (1)"],
  correctAnswer: 1,
},
{
  question: "A DOUBLE CHECK BACKFLOW PREVENTION ASSEMBLY WILL PROTECT THE POTABLE WATER SUPPLY FROM:",
  choices: ["NON-HEALTH HAZARD – BACKSIPHONAGE", "NON-HEALTH HAZARD – BACKPRESSURE", "NON-HEALTH HAZARD – BACKPRESSURE AND BACKSIPHONAGE", "HEALTH HAZARD – BACKSIPHONAGE", "HEALTH HAZARD – BACKPRESSURE"],
  correctAnswer: 2,
},
{
  question: "HOW MANY INCHES MUST AN ATMOSPHERIC VACUUM BREAKER BE INSTALLED ABOVE ALL DOWNSTREAM PIPING AND HIGHEST OPENING?",
  choices: ["SIX (6)", "NINE (9)", "TWELVE (12)", "EIGHTEEN (18)", "ONE (1)"],
  correctAnswer: 0,
},
{
  question: "AN ATMOSPHERIC VACUUM BREAKER IS INSTALLED TO PROTECT AGAINST:",
  choices: ["BACKPRESSURE – NON-HEALTH HAZARD CONDITIONS ONLY", "BACKPRESSURE – HEALTH HAZARD CONDITIONS ONLY", "BACKSIPHONAGE – NON-HEALTH HAZARD CONDITIONS ONLY", "BACKSIPHONAGE – HEALTH HAZARD CONDITIONS ONLY", "BACKSIPHONAGE – HEALTH HAZARD OR NON-HEALTH HAZARD CONDITIONS"],
  correctAnswer: 4,
},
{
  question: "THE TERM “APPROVED REDUCED PRESSURE PRINCIPLE ASSEMBLY”, APPLIES TO AN ASSEMBLY WITH TWO SHUT-OFF VALVES, FOUR TEST COCKS AND:",
  choices: ["TWO CHECK VALVES AND AN AIR INLET VALVE", "TWO APPROVED CHECK VALVES AND AN AIR INLET VALVE", "TWO APPROVED CHECK VALVES AND A PRESSURE RELIEF VALVE", "TWO APPROVED CHECK VALVES AND A DIFFERENTIAL PRESSURE RELIEF VALVE", "TWO APPROVED CHECK VALVES AND A PRESSURE REGULATING VALVE"],
  correctAnswer: 3,
},
{
  question: "IT IS REQUIRED THAT THE TEST GAUGE BE TESTED FOR ACCURACY AT LEAST:",
  choices: ["MONTHLY", "QUARTERLY", "SEMI-ANNUALLY", "ANNUALLY", "AT THE TIME OF PURCHASE AND PRIOR TO EACH USE FOR TESTING"],
  correctAnswer: 3,
},
{
  question: "UNDERSIZED WATER PIPING CARRYING WATER AT HIGH VELOCITY CAN CAUSE BACKSIPHONAGE DUE TO:",
  choices: ["THE VACUUM EFFECT", "THE PIVOT EFFECT", "THE MARGINAL EFFECT", "THE ASPIRATOR EFFECT", "THE VELOCITY EFFECT"],
  correctAnswer: 3,
},
{
  question: "AN AIR GAP SEPARATION IS MEASURED FROM THE OUTLET OF THE DISCHARGE PIPE, TO THE:",
  choices: ["FIXTURE DRAIN PLUG", "INLET OF THE SUPPLY", "LEVEL OF THE LIQUID", "FLOOD LEVEL RIM", "NONE OF THE ABOVE"],
  correctAnswer: 3,
},
{
  question: "THE MINIMUM TYPE OF CONTAINMENT PROTECTION FOR A NON-HEALTH HAZARD, NON-CHEMICAL FIRE SPRINKLER SYSTEM IS A(N):",
  choices: ["ATMOSPHERIC VACUUM BREAKER", "DOUBLE CHECK DETECTOR ASSEMBLY BACKFLOW PREVENTER", "PRESSURE VACUUM BREAKER ASSEMBLY", "REDUCED PRESSURE DETECTOR ASSEMBLY", "ALL OF THE ABOVE"],
  correctAnswer: 1,
},
{
  question: "THE TYPE OF PROTECTION REQUIRED FOR A CLOSED LOOP HEATING SYSTEM CONTAINING CHEMICALS IS:",
  choices: ["REDUCED PRESSURE PRINCIPLE ASSEMBLY", "DOUBLE CHECK VALVE ASSEMBLY", "PRESSURE VACUUM BREAKER ASSEMBLY", "DUAL CHECK VALVE TYPE BACKFLOW PREVENTER", "ALL OF THE ABOVE"],
  correctAnswer: 0,
},
{
  question: "FOR CONTAINMENT PROTECTION IN A NON-HEALTH HAZARD SITUATION, THE MINIMUM PROTECTION REQUIRED SHALL BE:",
  choices: ["REDUCED PRESSURE PRINCIPLE BACKFLOW PREVENTER", "TWO (2) SINGLE CHECK VALVES IN SERIES", "DOUBLE CHECK BACKFLOW PREVENTION ASSEMBLY", "ATMOSPHERIC VACUUM BREAKER", "NONE OF THE ABOVE"],
  correctAnswer: 2,
},
{
  question: "WATER CONTINUOUSLY LEAKING FROM TEST COCK #2 DURING A TEST PROCEDURE OF A PRESSURE VACUUM BREAKER ASSEMBLY IS  PROBABLY CAUSED BY A LEAKING:",
  choices: ["AIR INLET VALVE", "TEST COCK #1", "INLET SHUT-OFF VALVE #1", "OUTLET SHUT-OFF VALVE #2", "TEST COCK #2"],
  correctAnswer: 2,
},
{
  question: "THE REQUIRED BACKFLOW PREVENTION ASSEMBLY FOR A FIRE SUPPRESSION SYSTEM CONTAINING CHEMICALS IS:",
  choices: ["REDUCED PRESSURE DETECTOR ASSEMBLY OR REDUCED PRESSURE PRINCIPLE ASSEMBLY", "DOUBLE CHECK DETECTOR ASSEMBLY OR DOUBLE CHECK BACKFLOW PREVENTION ASSEMBLY", "PRESSURE VACUUM BREAKER ASSEMBLY", "DUAL CHECK VALVE TYPE BACKFLOW PREVENTER", "NONE OF THE ABOVE"],
  correctAnswer: 0,
},
{
  question: "THE REQUIRED TYPE OF BACKFLOW PROTECTION FOR A CLOSED LOOP PIPING SYSTEM CONTAINING GLYCOL IS:",
  choices: ["DOUBLE CHECK VALVE ASSEMBLY", "REDUCED PRESSURE PRINCIPLE ASSEMBLY", "ATMOSPHERIC VACUUM BREAKER", "DUAL CHECK VALVE TYPE BACKFLOW PREVENTER", "NONE OF THE ABOVE"],
  correctAnswer: 1,
},
{
  question: "THE PRIMARY CONSIDERATION IN DETERMINING WHAT TYPE OF BACKFLOW PREVENTER TO INSTALL IS:",
  choices: ["COST", "CUSTOMER PREFERENCE", "DEGREE OF HAZARD", "SYSTEM TEMPERTATURE", "PERSONAL PREFERENCE"],
  correctAnswer: 2,
},
{
  question: "WHAT IS THE PROBABLE CAUSE OF A RELIEF VALVE FAILING TO OPEN DURING A FIELD TEST ON A REDUCED PRESSURE PRINCIPLE BACKFLOW PREVENTER?",
  choices: ["A LEAKING #1 SHUT-OFF VALVE", "LOW WATER SUPPLY PRESSURE", "AIR TRAPPED INSIDE THE RELIEF VALVE", "EXCESSIVE BACKPRESSURE", "A MALFUNCTION OF THE RELIEF VALVE MECHANISM"],
  correctAnswer: 4,
},
{
  question: "THE REQUIRED BACKFLOW PROTECTION FOR A CHEMICALLY CHARGED SOLAR HEATING SYSTEM WITH AN EXPANSION TANK IS A(N):",
  choices: ["REDUCED PRESSURE PRINCIPLE ASSEMBLY", "ATMOSPHERIC VACUUM BREAKER", "DOUBLE CHECK BACKFLOW PREVENTION ASSEMBLY", "PRESSURE VACUUM BREAKER ASSEMBLY", "NONE OF THE ABOVE"],
  correctAnswer: 0,
},
{
  question: "THE TYPE OF PROTECTION ASSOCIATED WITH AN AIR GAP SEPARATION IS:",
  choices: ["BACKSIPHONAGE – NON-HEALTH HAZARD", "BACKSIPHONAGE – HEALTH HAZARD", "BACKPRESSURE – NON-HEALTH HAZARD", "BACKPRESSURE – HEALTH HAZARD", "ALL OF THE ABOVE"],
  correctAnswer: 4,
},
{
  question: "THE APPLICATION OF A PRESSURE VACUUM BREAKER ASSEMBLY IS FOR:",
  choices: ["BACKPRESSURE AND ISOLATION", "BACKSIPHONAGE AND ISOLATION", "BACKPRESSURE OR BACKSIPHONAGE AND ISOLATION", "CONTAINMENT ONLY", "NONE OF THE ABOVE"],
  correctAnswer: 1,
},
{
  question: "HOW MANY POUNDS OF PRESSURE PER SQUARE INCH ARE EXERTED AT THE BASE OF A COLUMN OF WATER THAT IS TWO (2) FEET TALL?",
  choices: ["0.33", "0.78", "0.86", "1.29", "1.44"],
  correctAnswer: 2,
},
{
  question: "A PRESSURE OF 75 PSI WOULD BE EQUIVALENT TO WHAT _________ HEAD OF WATER?",
  choices: ["37.5 FEET", "75.0 FEET", "115.0 FEET", "150.0 FEET", "173.2 FEET"],
  correctAnswer: 4,
},
{
  question: "A PRESSURE GAUGE INSTALLED AT THE BOTTOM OF AN OPEN TANK, CONTAINING WATER TEN (10) FEET DEEP, WOULD INDICATE WHAT PRESSURE READING?",
  choices: ["4.3 PSI", "8.6 PSI", "12.2 PSI", "14.7 PSI", "16.9 PSI"],
  correctAnswer: 0,
},
{
  question: "WHAT EQUIPMENT IS USED TO TEST A PRESSURE VACUUM BREAKER ASSEMBLY?",
  choices: ["ATMOSPHERIC VACUUM GAUGE", "DUPLEX GAUGE", "DIFFERENTIAL PRESSURE GAUGE", "PAIR OF BOURBON GAUGES", "FORTY-TWO INCH SIGHT TUBE"],
  correctAnswer: 2,
},
{
  question: "TEST COCK NUMBER __________ MAY BE OPENED TO ESTABLISH FLOW THROUGH A BACKFLOW PREVENTION ASSEMBLY:",
  choices: ["ONE (1)", "TWO (2)", "THREE (3)", "FOUR (4)", "ALL THE ABOVE"],
  correctAnswer: 3,
},
{
  question: "USC, AWWA AND MANUFACTURERS RECOMMEND THAT BACKFLOW PREVENTION ASSEMBLIES BE INSPECTED, AND THAT THEIR PROPER OPERATION IS VERIFIED BY A CERTIFIED TESTER AT LEAST:",
  choices: ["ONCE EVERY MONTH", "ONCE EVERY SIX (6) MONTHS", "ONCE EVERY YEAR", "ONCE EVERY TWO (2) YEARS", "ONCE EVERY THREE (3) YEARS"],
  correctAnswer: 2,
},
{
  question: "A DIFFERENTIAL PRESSURE GAUGE IS USED IN THE TESTING OF:",
  choices: ["DOUBLE CHECK VALVE ASSEMBLY", "OREDUCED PRESSURE PRINCIPLE BACKFLOW ASSEMBLY", "DUAL CHECK WITH INTERMEDIATE ATMOSPHERIC VENT", "BOTH A) AND B)", "ALL OF THE ABOVE"],
  correctAnswer: 3,
},
{
  question: "FROM THE CHOICES LISTED BELOW, WHAT INFORMATION IS REQUIRED TO PROPERLY IDENTIFY THE BACKFLOW PREVENTION ASSEMBLY TO BE TESTED?",
  choices: ["TYPE AND MANUFACTURER OF BACKFLOW PREVENTION ASSEMBLY", "LOCATION AND SIZE OF BACKFLOW PREVENTION ASSEMBLY", "MODEL AND SERIAL NUMBER OF BACKFLOW PREVENTION ASSEMBLY", "ALL OF THE ABOVE", "BOTH A) AND C)"],
  correctAnswer: 3,
},
{
  question: "THE ORIGINAL SIGNED AND DATED TEST REPORT MUST BE:",
  choices: ["GIVEN TO THE OWNER OF THE PROPERTY", "SUBMITTED TO THE WATER PURVEYOR",  "KEPT BY THE TESTER FOR THREE YEARS", "KEPT BY THE TESTER FOR TEN YEARS", "NONE OF THE ABOVE"],
  correctAnswer: 1,
},
{
  question: "THE CRITICAL FINAL STEP IN TESTING A BACKFLOW PREVENTION ASSEMBLY IS:",
  choices: ["REMOVING THE TEST COCK ADAPTERS", "RETURNING THE ASSEMBLY TO NORMAL OPERATING CONDITION", "RECORDING THE TEST RESULTS", "REMOVING THE GAUGES", "MAKING OUT THE BILL"],
  correctAnswer: 1,
},
{
  question: "THE DIFFERENTIAL PRESSURE RELIEF VALVE ON A REDUCED PRESSURE PRINCIPLE BACKFLOW  ASSEMBLY MUST OPEN BEFORE THE DIFFERENTIAL PRESSURE ACROSS THE INLET CHECK VALVE DROPS BELOW:",
  choices: ["1.0 PSID", "1.5 PSIA", "2.0 PSID", "2.5 PSIG", "NONE OF THE ABOVE"],
  correctAnswer: 2,
},
{
  question: "THE MINIMUM HOSE DIAMETER FOR A PRESSURE DIFFERENTIAL GAUGE IS ________ INCH:",
  choices: ["1/8", "1/4", "3/8", "1/2", "3/4"],
  correctAnswer: 1,
},
{
  question: "WHAT ARE THE MINIMUM SCALE INCREMENTS ALLOWED ON DIFFERENTIAL PRESSURE GAUGES USED FOR TESTING BACKFLOW PREVENTION ASSEMBLIES AND DEVICES?",
  choices: ["0.1 PSIA", "0.2 PSID", "0.5 PSIG", "1.0 PSID", "2.0 PSIA"],
  correctAnswer: 1,
},
{
  question: "WHAT VALVE MUST BE CLOSED WHEN TESTING A REDUCED PRESSURE PRINCIPLE BACKFLOW ASSEMBLY?",
  choices: ["NUMBER ONE (1) SHUT-OFF VALVE", "SERVICE CONNECTION VALVE", "PRESSURE REGULATING VALVE", "FLOW CONTROL VALVE", "NUMBER TWO (2) SHUT-OFF VALVE"],
  correctAnswer: 4,
},
{
  question: "AN OCCASIONAL DISCHARGE FROM THE RELIEF VALVE OF A REDUCED PRESSURE PRINCIPLE BACKFLOW PREVENTER USUALLY INDICATES:",
  choices: ["A LEAKING NUMBER ONE (1) CHECK VALVE", "A LEAKING NUMBER TWO (2) CHECK VALVE", "A MALFUNCTION IN THE RELIEF VALVE", "THE DEVICE IS WORKING PROPERLY", "AN IMPROPER INSTALLATION"],
  correctAnswer: 3,
},
{
  question: "IF THE CHECK VALVE SPRINGS ARE INTERCHANGED ON A DOUBLE CHECK VALVE ASSEMBLY, THE ASSEMBLY:",
  choices: ["WILL NOT PROTECT AGAINST BACKFLOW", "WILL CREATE A SIGNIFICANT PRESSURE DROP", "WILL NOT BE ADVERSELY AFFECTED BY THE INTERCHANGE", "WILL MALFUNCTION DUE TO THE INTERCHANGE", "WILL CREATE A STATIC CONDITION"],
  correctAnswer: 2,
},
{
  question: "CONSTANT DISCHARGE FROM THE RELIEF VALVE OF A REDUCED PRESSURE PRINCIPLE ASSEMBLY USUALLY INDICATES:",
  choices: ["FLUCTUATING INCOMING PRESSURE", "A LEAKING NUMBER ONE (1) CHECK VALVE", "FLUCTUATING DOWNSTREAM PRESSURE", "EXCESSIVE DOWNSTREAM PRESSURE", "THE SHUT-OFF VALVES ARE NOT OPEN"],
  correctAnswer: 1,
},
{
  question: "THE REQUIRED NUMBER OF TEST COCKS ON A SMALL (3/4”- 2”) PRESSURE VACUUM BREAKER ASSEMBLY IS:",
  choices: ["NONE", "ONE (1)", "TWO (2)", "THREE (3)", "FOUR (4)"],
  correctAnswer: 2,
},
{
  question: "THE REQUIRED NUMBER OF TEST COCKS ON A LARGE (2½” – 4”) ATMOSPHERIC VACUUM BREAKER IS:",
  choices: ["NONE", "ONE (1)", "TWO (2)", "THREE (3)", "FOUR (4)"],
  correctAnswer: 0,
},
{
  question: "WHAT CRITICAL COMPONENT OF AN ATMOSPHERIC VACUUM BREAKER IS SUBJECT TO FAILURE?",
  choices: ["UPSTREAM SHUT-OFF VALVE", "LOADED CHECK VALVE", "CANOPY", "AIR INLET VALVE", "DOWNSTREAM SHUT-OFF VALVE"],
  correctAnswer: 3,
},
{
  question: "A CHECK VALVE IN AN APPROVED BACKFLOW PREVENTION ASSEMBLY, MUST BE DRIP TIGHT WHEN:",
  choices: ["THE ASSEMBLY IS SUBJECT TO ANY BACKFLOW", "THE SUPPLY PRESSURE IS INCREASED", "THE NUMBER ONE (1) SHUT-OFF VALVE IS CLOSED", "THE TEST COCKS ARE OPEN", "THERE IS ANY ATTEMPTED WATER USAGE"],
  correctAnswer: 0,
},
{
  question: "A LEAKING CHECK VALVE MAY BE CAUSED BY A:",
  choices: ["DIRTY OR DAMAGED CHECK DISC", "DAMAGED CHECK SEAT", "BROKEN OR DAMAGED SPRING", "GUIDE MEMBERS HANGING UP", "ALL OF THE ABOVE"],
  correctAnswer: 4,
},
{
  question: "TEST COCK NUMBER ONE (1) OF AN APPROVED DOUBLE CHECK VALVE ASSEMBLY, IS LOCATED:",
  choices: ["DOWNSTREAM OF SHUT-OFF VALVE NUMBER ONE (1)", "DOWNSTREAM OF SHUT-OFF VALVE NUMBER TWO (2)", "UP STREAM OF SHUT-OFF VALVE NUMBER ONE (1)", "BETWEEN THE NUMBER ONE (1) AND NUMBER TWO (2) CHECK VALVES", "UPSTREAM OF THE DISCHARGE PORT"],
  correctAnswer: 2,
},
{
  question: "ON AN APPROVED PRESSURE VACUUM BREAKER ASSEMBLY, THE SHUT-OFF VALVES:",
  choices: ["ARE INSTALLED AT THE INLET OF THE ASSEMBLY ONLY", "ARE NOT USED DURING A FIELD TEST PROCEDURE", "ARE INSTALLED AT THE OUTLET OF THE ASSEMBLY ONLY", "CONTAIN AN INLET TEST COCK ON ALL ASSEMBLIES", "ARE LOCATED AT THE INLET AND OUTLET OF ALL ASSEMBLIES"],
  correctAnswer: 4,
},
{
  question: "TEST COCK NUMBER ONE (1) ON A SMALL (3/4” – 2”) PRESSURE VACUUM BREAKER ASSEMBLY, IS LOCATED BETWEEN THE CHECK VALVE AND THE:",
  choices: ["AIR INLET VALVE", "INLET VALVE COVER", "SHUT-OFF VALVE NUMBER ONE (1)", "SHUT-OFF VALVE NUMBER TWO (2)", "TEST COCK NUMBER TWO (2)"],
  correctAnswer: 2,
},
{
  question: "TEST COCK NUMBER TWO (2) ON A PRESSURE VACUUM BREAKER ASSEMBLY IS LOCATED BETWEEN THE AIR INLET VALVE AND THE:",
  choices: ["DOWNSTREAM CHECK VALVE", "INLET SHUT-OFF VALVE NUMBER TWO (2)", "TEST COCK NUMBER ONE (1)", "OUTLET SHUT OFF VALVE NUMBER TWO (2)",  "UPSTREAM CHECK VALVE"],
  correctAnswer: 4,
},
{
  question: "WHEN TESTING WITH A DIFFERENTIAL PRESSURE GAUGE, A PRESSURE VACUUM BREAKER ASSEMBLY AIR INLET VALVE, WATER PRESSURE IS BLED THROUGH THE:",
  choices: ["INLET SHUT-OFF VALVE NUMBER ONE (1)",  "OUTLET SHUT-OFF VALVE NUMBER TWO (2)", "TEST COCK NUMBER ONE (1)", "DIFFERENTIAL GAUGE", "AIR INLET VALVE"],
  correctAnswer: 3,
},
{
  question: "TEST COCKS ARE FLUSHED FOR THE FOLLOWING REASON(S):",
  choices: ["TO DETERMINE FLOW THROUGH THE DEVICE", "TO PROTECT THE TEST GAUGES FROM DAMAGE", "TO REMOVE LODGED FOREIGN MATERIAL", "TO DETERMINE THAT THE TEST COCKS ARE NOT PLUGGED", "ALL OF THE ABOVE"],
  correctAnswer: 4,
},
{
  question: "THE RELIEF VALVE OF A REDUCED PRESSURE PRINCIPLE BACKFLOW ASSEMBLY IS INTERNALLY LOADED TO:",
  choices: ["REDUCE THE INCOMING PRESSURE", "FORCE THE NUMBER TWO (2) CHECK VALVE TO OPEN", "FORCE THE RELIEF VALVE TO OPEN", "FORCE THE NUMBER ONE (1) CHECK VALVE TO OPEN", "FORCE THE RELIEF VALVE TO CLOSE"],
  correctAnswer: 2,
},
{
  question: "A REDUCED PRESSURE PRINCIPLE BACKFLOW ASSEMBLY’S DIFFERENTIAL RELIEF VALVE OPERATES FROM THE INCOMING WATER PRESSURE AND THE WATER PRESSURE IN THE:",
  choices: ["NUMBER TWO (2) SHUT-OFF VALVE",  "ATMOSPHERIC VENT", "NUMBER FOUR (4) TEST COCK", "ZONE BETWEEN THE TWO CHECK VALVES", "MOST REMOTE FIXTURE SERVED BY THE DEVICE"],
  correctAnswer: 3,
},
{
  question: "A REDUCED PRESSURE PRINCIPLE BACKFLOW ASSEMBLY TEST WILL INDICATE A LEAKING NUMBER TWO (2) SHUT-OFF VALVE BY:",
  choices: ["AN INCREASE IN THE DIFFERENTIAL PRESSURE READING", "A DIFFERENTIAL PRESSURE DROP TO ZERO (0) PSIG", "A DROP OF ONE (1) PSID PRESSURE", "A DROP IN DIFFERENTIAL PRESSURE AND RELIEF VALVE DISCHARGE", "NO CHANGE IN THE DIFFERENTIAL PRESSURE READING WHEN TESTING THE DIFFERENTIAL PRESSURE RELIEF VALVE"],
  correctAnswer: 4,
},
{
  question: "HOW CAN YOU STOP AN OCCASIONAL DISCHARGE OF WATER FROM THE RELIEF VALVE OF A REDUCED PRESSURE PRINCIPLE BACKFLOW PREVENTER CAUSED BY SUPPLY PRESSURE FLUCTUATIONS?",
  choices: [A)     "BY INSTALLING A PRESSURE REGULATING VALVE ON THE SUPPLY PIPE", "BY INSTALLING A SOFT SEAT CHECK VALVE UPSTREAM OF THE ASSEMBLY", "BY INSTALLING A GLOBE VALVE ON THE DOWNSTREAM PIPING", "BY INSTALLING A SOFT SEAT CHECK VALVE DOWNSTREAM OF THE ASSEMBLY", "BY INSTALLING A STRAINER UPSTREAM OF THE ASSEMBLY"],
  correctAnswer: 1,
},
{
  question: "THE TERM COPPER POISONING RESULTS FROM:",
  choices: ["THE CHEMICAL REACTION OF COPPER PIPING MATERIALS TO CONTAMINATED WATER",  "THE CHEMICAL REACTION OF COPPER PIPING MATERIALS TO PLASTIC PIPE", "THE CHEMICAL REACTION OF COPPER PIPING MATERIALS TO POLLUTED WATER", "THE CHEMICAL REACTION OF COPPER PIPING MATERIALS TO CO2", "NONE OF THE ABOVE"],
  correctAnswer: 3,
},
{
  question: "PSIG IS EQUIVALENT TO:",
  choices: ["PSIA PLUS ATMOSPHERIC PRESSURE", "THE PRESSURE ON A PSIA GAUGE, ABOVE OR BELOW ATMOSPHERIC PRESSURE", "THE PRESSURE ON A PSIA GAUGE, ABOVE SEA LEVEL", "PSIA MINUS ATMOSPHERIC PRESSURE", "NONE OF THE ABOVE"],
  correctAnswer: 3,
},
{
  question: "A SMALL HOLE IN THE UNDERGROUND POTABLE WATER DISTRIBUTION SYSTEM MAY:",
  choices: ["REDUCE THE INCOMING PRESSURE SIGNIFICANTLY", "ALLOW CONTAMINATION OF THE SYSTEM FROM BACKSIPHONAGE BACKFLOW", "CREATE BACKPRESSURE BACKFLOW", "INCREASE THE SYSTEM PRESSURE", "CAUSE THE DISTRIBUTION SYSTEM PUMPS TO SIPHON AIR"],
  correctAnswer: 1,
},
{
  question: "IT IS POSSIBLE TO COMPENSATE FOR A LEAKING NUMBER TWO (2) SHUT-OFF VALVE DURING THE FIELD TEST PROCEDURE OF A REDUCED PRESSURE PRINCIPLE BACKFLOW PREVENTER BY ATTACHING A TEMPORARY BYPASS HOSE FROM:",
  choices: ["NUMBER ONE TEST COCK TO NUMBER THREE (3) TEST COCK", "NUMBER TWO (2) TEST COCK TO NUMBER FOUR (4) TEST COCK", "NUMBER TWO (2) TEST COCK TO THE ANGLE STOP OF THE FIRST UPSTREAM FIXTURE", "NUMBER ONE (1) TEST COCK TO NUMBER FOUR (4) TEST COCK", "NUMBER THREE (3) TEST COCK TO NUMBER FOUR (4) TEST COCK"],
  correctAnswer: 3,
},
{
  question: "EDIBLE SYRUP INTRODUCED INTO A WATER SYSTEM THROUGH A CROSS-CONNECTION WOULD BE AN EXAMPLE OF:",
  choices: ["A NUISANCE", "A HEALTH HAZARD", "A NON-HEALTH HAZARD", "THE VENTURI EFFECT", "CONTAMINATION HAZARD"],
  correctAnswer: 2,
},
{
  question: "ALL OF THE FOLLOWING COULD CREATE A CLOSED LOOP PIPING SYSTEM EXCEPT A:",
  choices: ["PRESSURE RELIEF VALVE", "GATE VALVE", "DUAL CHECK VALVE TYPE BACKFLOW PREVENTER", "DOUBLE CHECK VALVE BACKFLOW PREVENTION ASSEMBLY", "BALL VALVE WITH AN INTEGRAL TEST PORT ON THE OUTLET SIDE OF THE VALVE"],
  correctAnswer: 0,
},
{
  question: "POINT OF USE BACKFLOW PREVENTION IS DEFINED AS:",
  choices: [\"UNNECESSARY", "INTERMITTENT", "CONTAINMENT", "HAZARD ASSESSMENT", "ISOLATION"],
  correctAnswer: 4,
},
{
  question: "AN AIR GAP SEPARATION IS DETERMINED FROM THE OUTLET PIPING’S _____________ DIAMETER.",
  choices: ["INSIDE", "OUTSIDE", "EFFECTIVE", "NOMINAL", "GREATEST"],
  correctAnswer: 2,
},
{
  question: "IF NOT MARKED, THE CRITICAL LEVEL (CL) OF A PRESSURE VACUUM BREAKER ASSEMBLY IS ASSUMED TO BE THE LEVEL OF THE:",
  choices: ["AIR INLET VALVE", "BOTTOM OF THE INLET PIPING", "SHUT-OFF VALVE NUMBER TWO (2)", "BOTTOM OF THE VALVE BODY", "BOTTOM OF THE DISCHARGE PIPING"],
  correctAnswer: 3,
},
{
  question: "THE REASON FOR THE METER ON A DOUBLE CHECK DETECTOR ASSEMBLY BACKFLOW PREVENTER IS TO:",
  choices: ["DETECT ANY BACKFLOW", "BYPASS THE WATER METER", "TEST THE ALARM SYSTEM", "DETERMINE THE DIRECTION OF FLOW", "DETECT UNAUTHORIZED WATER USAGE"],
  correctAnswer: 4,
},
{
  question: "A SPILL RESISTANT VACUUM BREAKER (SVB) IS A MODIFIED:",
  choices: ["DOUBLE CHECK BACKFLOW PREVENTION ASSEMBLY", "REDUCED PRESSURE PRINCIPLE BACKFLOW ASSEMBLY", "PRESSURE VACUUM BREAKER ASSEMBLY", "AIR GAP SEPARATION", "ATMOSPHERIC VACUUM BREAKER"],
  correctAnswer: 2,
},
{
  question: "THE MINIMUM VERTICAL DISTANCE BETWEEN THE RELIEF VALVE DISCHARGE PORT OF A REDUCED PRESSURE PRINCIPLE BACKFLOW  ASSEMBLY AND THE FLOOR PLANE IS:",
  choices: ["SIX (6) INCHES", "TWELVE (12) INCHES", "EIGHTEEN (18) INCHES", "TWENTY-FOUR (24) INCHES", "THIRTY (30) INCHES"],
  correctAnswer: 1,
},
{
  question: "THE MINIMUM REQUIREMENT FOR AN APPROVED AIR GAP SEPARATION SHALL BE AT LEAST:",
  choices: ["ONE HALF THE DIAMETER OF THE SUPPLY PIPE", "SIX (6) INCHES ABOVE THE OUTLET OF THE SUPPLY PIPE", "TWICE THE DIAMETER OF THE SUPPLY PIPE, BUT NOT LESS THAN ONE (1) INCH", "TWELVE (12) INCHES ABOVE THE SURROUNDING GROUND OR FLOOR", "THAT RECOMMENDED BY THE MANUFACTURER OF THE PHYSICAL AIR GAP"],
  correctAnswer: 2,
},
{
  question: "THE TYPE OF PROTECTION PROVIDED BY A BAROMETRIC LOOP IS:",
  choices: ["PREVENTS BACKPRESSURE BACKFLOW", "IT PROVIDES AN ATMOSPHERIC BREAK", "PREVENTS BACKSIPHONAGE BACKFLOW", "PREVENTS BACKPRESSURE AND BACKSIPHONAGE BACKFLOW", "THAT IT ENSURES THE REQUIRED PRESSURE DROP DOWNSTREAM OF THE LOOP"],
  correctAnswer: 2,
},
{
  question: "THE PROPER INSTALLATION OF AN ATMOSPHERIC VACUUM BREAKER ON AN IRRIGATION SYSTEM WOULD PERMIT THE DOWNSTREAM PIPING TO BE ELEVATED ABOVE THE ATMOSPHERIC VACUUM BREAKER, PROVIDED:",
  choices: ["THERE ARE NO CONTROL VALVES DOWNSTREAM", "THE SPRINKLER HEADS ARE AT LEAST SIX (6) INCHES BELOW THE AVB", "A HOSE BIB IS INSTALLED DOWNSTREAM TO DRAIN THE PIPING", "A SHUT-OFF VALVE IS INSTALLED DOWNSTREAM, PRIOR TO THE SPRINKLER HEADS", "THIS IS NEVER AN ACCEPTABLE PRACTICE"],
  correctAnswer: 4,
},
{
  question: "EVERY VACUUM BREAKER IS DESIGNED TO:",
  choices: ["PREVENT ATMOSPHERE FROM ENTERING THE DOWNSTREAM SYSTEM", "PREVENT BACKSIPHONAGE BACKFLOW", "PREVENT BACKPRESSURE BACKFLOW",  "PREVENT BACKSIPHONAGE AND BACK-PRESSURE BACKFLOW", "PROMOTE AND ALLOW SIPHONAGE UNDER ANY CONDITION"],
  correctAnswer: 1,
},
{
  question: "AN UNPROTECTED BYPASS AROUND A BACKFLOW PREVENTION ASSEMBLY OR DEVICE:",
  choices: ["IS CONSIDERED TO BE A CROSS-CONNECTION AND IS NEVER PERMITTED", "MUST BE WITHIN THREE (3) FEET OF THE DEVICE TO ALLOW INSPECTION", "MUST BE EQUIPPED WITH A SWING OR SPRING LOADED CHECK VALVE", "MUST BE OF AN EQUIVALENT PIPE SIZE", "SHALL BE PROVIDED WITH FULL PORT VALVES TO ALLOW FOR ISOLATION AND REPAIR"],
  correctAnswer: 0,
},
{
  question: "A POTENTIAL BACKPRESSURE BACKFLOW PLUMBING CONNECTION IS A(N):",
  choices: ["PROCESS WATER LINE", "ASPIRATOR",  "WATER CLOSET", "FLUSHOMETER", "MOP SINK WITH AN OPEN END HOSE CONNECTED"],
  correctAnswer: 0,
},
{
  question: "WHEN TESTING A SPILL RESISTANT VACUUM BREAKER (SVB) THE __________ IS TESTED BY REMOVING THE VENT SCREW",
  choices: ["THE #2 CHECK VALVE", "THE AIR INLET VALVE", "THE #1 SHUTOFF VALVE", "THE CHECK VALVE", "NONE OF THE ABOVE"],
  correctAnswer: 3,
},
{
  question: "WHICH FACILITY MAY NOT BE REQUIRED TO INSTALL A REDUCED PRESSURE PRINCIPLE BACKFLOW PREVENTION ASSEMBLY ON THEIR SERVICE CONNECTION:",
  choices: ["COMMERCIAL CAR WASH", "SEWAGE TREATMENT PLANT", "CHEMICAL OR PLATING PLANT", "A TALL BUILDING WHERE THE HIGHEST OUTLET IS 80 FT OR MORE ABOVE THE METER", "HOSPITAL"],
  correctAnswer: 3,
},
{
  question: "A CHEMICALLY TREATED BOILER SYSTEM WOULD REQUIRE WHAT TYPE OF BACKFLOW PROTECTION ON THE POTABLE WATER MAKE-UP LINE:",
  choices: ["DOUBLE CHECK VALVE ASSEMBLY", "REDUCED PRESSURE PRINCIPLE BACKFLOW ASSEMBLY", "DUAL CHECK VALVE TYPE BACKFLOW PREVENTER", "BACKFLOW PREVENTER WITH INTERMEDIATE ATMOSPHERIC VENT", "AN APPROVED DETECTOR CHECK WITH AN INTEGRAL ALARM"],
  correctAnswer: 1,
},
{
  question: "THE RECOMMENDED BACKFLOW PROTECTION FOR THE POTABLE WATER SUPPLY TO A PUMP USED FOR HANDLING RAW SEWAGE IS A(N):",
  choices: ["DOUBLE CHECK DETECTOR ASSEMBLY BACKFLOW PREVENTER", "AIR GAP",  "REDUCED PRESSURE PRINCIPLE BACKFLOW PREVENTER", "PRESSURE VACUUM BREAKER ASSEMBLY", "ATMOSPHERIC VACUUM BREAKER"],
  correctAnswer: 1,
},
{
  question: "THE POTABLE WATER SUPPLY TO A URINAL EQUIPPED WITH A FLUSHOMETER VALVE IS NORMALLY PROTECTED BY A(N):",
  choices: ["REDUCED PRESSURE PRINCIPLE BACKFLOW PREVENTION ASSEMBLY", "DOUBLE CHECK BACKFLOW PREVENTION ASSEMBLY", "ATMOSPHERIC VACUUM BREAKER", "DUAL CHECK VALVE TYPE BACKFLOW PREVENTER", "PRESSURE VACUUM BREAKER ASSEMBLY"],
  correctAnswer: 2,
},
{
  question: "AN ABSOLUTE VACUUM AT SEA LEVEL CAN LIFT A COLUMN OF WATER A MAXIMUM DISTANCE OF:",
  choices: ["2.3 FEET",  "4.34 FEET", "14.7 FEET", "33.9 FEET", "8.33 FEET"],
  correctAnswer: 3,
},
{
  question: "WHEN TESTING A DOUBLE CHECK VALVE BACKFLOW PREVENTION ASSEMBLY, THE NUMBER TWO (2) SHUT-OFF VALVE MUST BE CLOSED FIRST TO:",
  choices: ["PREVENT BACKPRESSURE DURING THE TEST", "PREVENT BACKSIPHONAGE DURING THE TEST", "MAINTAIN ZERO (0) PSIG AT THE OUTLET", "HOLD WATER IN THE DOWNSTREAM PIPING", "MAINTAIN PRESSURE IN THE ASSEMBLY"],
  correctAnswer: 4,
},
{
  question: "WHILE TESTING A REDUCED PRESSURE PRINCIPLE BACKFLOW ASSEMBLY, A FLUCTUATION IN THE PRESSURE DIFFERENTIAL DURING A STATIC CONDITION IS CAUSED BY:",
  choices: ["RAPIDLY CHANGING SUPPLY PRESSURE", "BACKPRESSURE BACKFLOW", "LEAKING NUMBER ONE (1) CHECK VALVE", "BACKSIPHONAGE BACKFLOW", "LEAKING NUMBER TWO (2) CHECK VALVE"],
  correctAnswer: 0,
},
{
  question: "THE WEIGHT OF A CUBIC FOOT OF WATER AT SEA LEVEL IS:",
  choices: ["7.5 POUNDS", "8.33 POUNDS", "33.9 POUNDS",  "62.4 POUNDS", "EASILY MEASURED WITH A DIFFERENTIAL PRESSURE GAUGE"],
  correctAnswer: 3,
},
{
  question: "AN ABSOLUTE PRESSURE OF TWENTY-FIVE (25) PSIA (AT SEA LEVEL) IS EQUAL TO APPROXIMATELY:",
  choices: ["FIVE (5) PSIG", "TEN (10) PSIG", "FIFTEEN (15) PSIG", "TWENTY (20) PSIG", "TWENTY-FIVE (25) PSIG"],
  correctAnswer: 1,
},
{
  question: "TO EXERT A PRESSURE OF ONE (1) PSIG AT THE BASE OF A COLUMN OF WATER, THE COLUMN OF WATER WOULD HAVE TO BE _____ IN HEIGHT:",
  choices: ["4.34 INCHES", "12.0 INCHES", "14.7 INCHES", "27.75 INCHES", "TEN (10) FEET"],
  correctAnswer: 3,
},
{
  question: "WHEN TESTING A BACKFLOW PREVENTION ASSEMBLY, THE TESTER MUST FIRST:",
  choices: ["CLOSE THE SHUT-OFF VALVES", "RECORD THE SERIAL NUMBER", "DETERMINE THE DIRECTION OF FLOW", "NOTIFY THE OWNER",  "FLUSH THE TEST COCK"],
  correctAnswer: 3,
},
{
  question: "IF DURING THE FIELD TEST OF A REDUCED PRESSURE PRINCIPLE BACKFLOW ASSEMBLY, THE RELIEF VALVE FAILS TO OPEN, THE PROBABLE CAUSE IS:",
  choices: ["A MALFUNCTION OF THE DIFFERENTIAL PRESSURE RELIEF VALVE MECHANISM", "A LEAKING NUMBER ONE (1) CHECK VALVE", "THE TESTER FORGOT TO BLEED THE TEST COCKS PRIOR TO TESTING", "AIR TRAPPED INSIDE THE RELIEF VALVE", "BOTH C) AND D)"],
  correctAnswer: 0,
},
{
  question: "WHEN FIELD TESTING THE AIR INLET VALVE ON A PRESSURE VACUUM BREAKER ASSEMBLY, THE TEST GAUGE ELEVATION SHALL BE:",
  choices: ["AT LEAST SIX (6) INCHES HIGHER THAN THE ASSEMBLY", "THE SAME LEVEL AS THE ASSEMBLY", "THE SAME LEVEL AS THE AIR INLET VALVE", "AT LEAST TWELVE (12) INCHES HIGHER THAN THE ASSEMBLY", "ALWAYS LOWER THAN THE DEVICE OR ASSEMBLY BEING TESTED"],
  correctAnswer: 2,
},
{
  question: "IF THE AIR INLET VALVE OF A PRESSURE VACUUM BREAKER ASSEMBLY WILL NOT SEAT, THE:",
  choices: ["AIR INLET VALVE SHOULD BE PHYSICALLY MANIPULATED UNTIL IT OPERATES PROPERLY", "CHECK VALVE SHOULD BE REMOVED AND CHECKED FOR PROPER SPRING TENSION", "CANOPY COVER MUST BE REPLACE AND SPECIFIED CLEARANCES VERIFIED", "SUPPLY PRESSURE IS TOO LOW", "AIR INLET VALVE MUST BE REMOVED"],
  correctAnswer: 3,
},
{
  question: "THE SPRINGS ON THE TWO (2) CHECK VALVES OF A REDUCED PRESSURE PRINCIPLE BACKFLOW PREVENTER ARE:",
  choices: ["LOCATED OUTSIDE THE BODY OF THE ASSEMBLY", "EXTERNALLY LOADED", "ARE NOT INTERCHANGEABLE", "MECHANICALLY INTERCONNECTED", "ARE INTERCHANGEABLE"],
  correctAnswer: 2,
},
{
  question: "THE NUMBER TWO (2) TEST COCK OF A DOUBLE CHECK VALVE ASSEMBLY IS LOCATED:",
  choices: ["UPSTREAM OF SHUT-OFF VALVE NUMBER ONE (1)", "DOWNSTREAM OF SHUT-OFF VALVE NUMBER ONE (1) AND UPSTREAM OF CHECK VALVE NUMBER ONE (1)", "DOWNSTREAM OF SHUT-OFF VALVE NUMBER TWO (2)", "DOWNSTREAM OF THE NUMBER TWO (2) CHECK VALVE AND UPSTREAM OF NUMBER TWO (2) SHUT-OFF VALVE", "BETWEEN THE NUMBER ONE (1) AND NUMBER TWO (2) CHECK VALVE"],
  correctAnswer: 1,
},
{
  question: "A TWO (2) INCH ATMOSPHERIC VACUUM BREAKER, INSTALLED ON A TWO (2) INCH WATER SUPPLY TO A TANK MUST BE AT LEAST _________ ABOVE THE FLOOD LEVEL RIM OF THE TANK:",
  choices: ["TWO (2) INCHES", "FOUR (4) INCHES", "SIX (6) INCHES", "TWELVE (12) INCHES", "TWENTY-FOUR (24) INCHES"],
  correctAnswer: 2,
},
{
  question: "A 1/4 INCH DIAMETER POTABLE WATER SUPPLY SHALL HAVE AT LEAST A _________ AIR GAP SEPARATION BETWEEN THE SUPPLY PIPE AND THE FLOOD LEVEL RIM:",
  choices: ["ONE HALF (1/2) INCH", "ONE(1) INCH", "TWO (2) INCH", "SIX (6) INCH", "ONE QUARTER (1/4) INCH"],
  correctAnswer: 1,
},
{
  question: "THE FOLLOWING IS AN ACCEPTABLE BACKFLOW PREVENTION DEVICE IN THE STATE OF TEXAS:",
  choices: ["A VENTED DUAL CHECK", "TWO (2) CHECK VALVES, FABRICATED AND INSTALLED BY A LICENSED PLUMBER", "A STAINLESS BALL CHECK WITH A MINIMUM FIVE (5) PSI SPRING TENSION", "SPRING CHECKS ON VERTICAL PIPING", "NONE OF THE ABOVE"],
  correctAnswer: 4,
},
];

//Variables
var startButton = document.getElementById("start-button");
var timerSpan = document.getElementById("time-left");
var timerElement = document.getElementById("timer");
var timeLeft = 100;
var gameInterval;

//Track current question and user's score
var currentQuestion = 0;
var score = 0;

//Function to start game
function startGame() {
    startButton.style.display = "none";
    gameInterval = setInterval(function() {
      timeLeft--;
      timerElement.textContent = "Time Remaining: " + timeLeft + " seconds";
      if (timeLeft <= 0) {
        clearInterval(gameInterval);
        showFinalScore();
      }
    }, 1000);
  }

//Function to display the current question and choices
function displayQuestion() {
    var questionElement = document.getElementById("question");
    var choicesElement = document.getElementById("choices");

    questionElement.textContent = "";
    choicesElement.innerHTML = "";

    questionElement.textContent = quizQuestions[currentQuestion].question;

    for (var i = 0; i < quizQuestions[currentQuestion].choices.length; i++) {
        var choices = document.createElement("li");
        choices.textContent = quizQuestions[currentQuestion].choices[i];
        choices.setAttribute("data-index", i)
        choices.onclick = checkSelectedAnswer;
        choicesElement.appendChild(choices);
    }
    }

//Function to check the selected answer and increase score
function checkSelectedAnswer() {
    var selectedOption = parseInt(this.getAttribute("data-index"));
    
    if (selectedOption === quizQuestions[currentQuestion].correctAnswer) {
      score++;
      this.textContent = "CORRECT!";
      this.classList.remove("wrong");
      this.classList.add("correct");
    } else {
      this.textContent = "WRONG!";
      this.classList.remove("correct");
      this.classList.add("wrong");
      timeLeft -= 10;
      if (timeLeft < 0) {
        timeLeft = 0;
      }
    }

//Move to the next question or show the final score
    currentQuestion++;

    if (currentQuestion < quizQuestions.length) {
        setTimeout(displayQuestion, 1000);
    } else {
      clearInterval(gameInterval);
      showFinalScore();
    }
  }

//Function to show the final score
function showFinalScore() {
    var questionElement = document.getElementById("question");
    var choicesElement = document.getElementById("choices");

    var finalScore = timeLeft;
    var showFinalScoreElement = document.createElement("p");
    showFinalScoreElement.textContent = "Your Score: " + finalScore + "!";
    showFinalScoreElement.id = "final-score";
    document.body.appendChild(showFinalScoreElement);

    questionElement.textContent = "";
    choicesElement.innerHTML = "";

//Promt player to enter initals
    alert("Your Score: " + finalScore +"!");
    var playerInitials = prompt("Enter your initials:");
    if (finalScore <= 45) {alert("Nice Try! Keep Studying!");
    }
    else alert("WOW! That was AMAZING!!")

//Store the plyer initals and high score in local storage
    localStorage.setItem("playerInitials", playerInitials);
    localStorage.setItem("highScore", finalScore);
    window.location.href = "highscores.html";

}

startButton.addEventListener("click", function() {
    startGame();
    displayQuestion();
    alert("Wrong answers will deduct 10 seconds from the clock. Score is based on how much time you have left. Are you ready?")
})